Remove fms release-jcsda versions from config templates
JCSDA/spack-stack pull request #1197
Opened 2024-07-11 19:32 UTC by srherbener

### Summary

This PR removes the fms `release-jcsda` versions from the unified-dev and skylab-dev config templates. These versions are no longer needed given the recent switch to the fms 2023.04 version.

### Testing

### Applications affected

Skylab, fv3 model variants

### Systems affected

HPC, Linux and Mac platforms

### Dependencies

None

### Issue(s) addressed

Partially addresses #548

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [ ] These changes have been tested on the affected systems and applications.
- [ ] All dependency PRs/issues have been resolved and this PR can be merged.

2024-07-11 19:41 UTC, climbfuji requested changes
That's necessary, but not enough. Some of the spack-ext virtual environments explicitly ask for fms@release-jcsda.

2024-07-11 19:46 UTC, climbfuji commented
> That's necessary, but not enough. Some of the spack-ext virtual environments explicitly ask for fms@release-jcsda.

Also, as part of this PR we should update the spack submodule to make the fms package identical to what is in spack develop (maybe have to pull in updates from spack develop first and then remove our custom release-jcsda addition).

2024-07-12 16:18 UTC, srherbener commented
> That's necessary, but not enough. Some of the spack-ext virtual environments explicitly ask for fms@release-jcsda.

I'm not finding the release-jcsda versions in the spack-ext. 
```
MacBook-Pro-5:spack-stack steveherbener$ grep -i -R fms spack-ext
spack-ext/repos/spack-stack/packages/ufs-srw-app-env/package.py:    depends_on("fms@2023.04")
spack-ext/repos/spack-stack/packages/ufs-weather-model-env/package.py:    depends_on("fms@2023.04", type="run")
spack-ext/repos/spack-stack/packages/jedi-ufs-env/package.py:    depends_on("fms@2023.04+pic", type="run")
spack-ext/repos/spack-stack/packages/gmao-swell-env/package.py:    depends_on("fms@2023.04+pic", type="run")
spack-ext/repos/spack-stack/packages/jedi-fv3-env/package.py:    depends_on("fms@2023.04+pic", type="run")
```
Am I missing something? Thanks!

2024-07-12 16:25 UTC, AlexanderRichert-NOAA commented
This is a welcome development :) At this point, can `fms@2023.04` be pinned in common/packages.yaml and remove the fms entry from unified-dev altogether?

2024-07-12 16:31 UTC, climbfuji commented
> This is a welcome development :) At this point, can `fms@2023.04` be pinned in common/packages.yaml and remove the fms entry from unified-dev altogether?

Yes. Apologies @srherbener I forgot I already made the change I asked you for in spack-ext and in the container config. Embarrassing. If you could remove the varous @2023.04 (including +pic) that you found in spack-ext, and then make sure configs/common/packages.yaml requires fms@2023.04 +pic (and the other variants already there), please?

2024-07-12 16:53 UTC, srherbener commented
> > That's necessary, but not enough. Some of the spack-ext virtual environments explicitly ask for fms@release-jcsda.
> 
> Also, as part of this PR we should update the spack submodule to make the fms package identical to what is in spack develop (maybe have to pull in updates from spack develop first and then remove our custom release-jcsda addition).

Done. See https://github.com/JCSDA/spack/pull/451

2024-07-12 17:31 UTC, srherbener commented
> This is a welcome development :) At this point, can `fms@2023.04` be pinned in common/packages.yaml and remove the fms entry from unified-dev altogether?

Does "pin" mean to add a `require @2023.04` line to the YAML? Just want to double check. Thanks!

2024-07-12 17:39 UTC, srherbener commented
Okay, I think I got the changes that both @AlexanderRichert-NOAA and @climbfuji requested. Please take a look and let me know if there is anything else. Thanks!

2024-07-12 17:49 UTC, AlexanderRichert-NOAA approved these changes

2024-07-12 18:36 UTC, climbfuji commented
I merged the spack PR ... you know the drill ;-)

2024-07-12 19:44 UTC, srherbener commented
> I merged the spack PR ... you know the drill ;-)

Done

2024-07-12 19:51 UTC, climbfuji approved these changes

2024-07-12 20:47 UTC, merged