Add github CLI to unified-dev and skylab-dev
JCSDA/spack-stack pull request #1270
Opened 2024-08-23 04:20 UTC by eap

Add the github-cli to unified-dev and skylab-dev templates.

This package is added as a root package (rather than via a meta-package) since many users already have access to the github CLI and we don't want to load it automatically and instead anyone needing this tool should have to intentionally load it into the environment.

### Testing

* Using an unsubmitted comparison shell tool (coming soon) I compared the spack lock files of the unified-dev environment before and after addition of the gh command line tool to the template. No dependences are added or changed (other than `gh`) in order to include this CLI tool
* I built and ran this code on an ubuntu 22.04 host in the unified-dev environment.

### Issue(s) addressed

Fixes: #1105

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [x] All dependency PRs/issues have been resolved and this PR can be merged.

2024-08-23 12:55 UTC, climbfuji requested changes
I noticed CI is failing, can you check please?

Also, I am torn. We should check the original issue, and if the users requesting gh cli want it for a specific application (e.g. global workflow), then it should either go in that virtual package or higher up in the tree if more applications want it.

The goal is to be able to load a single module (after the stack-* metamodules) such as `module load global-workflow-env` and having access to everything that is needed. Users shouldn't have to know all dependencies themselves, that's our job.

2024-08-23 12:55 UTC, climbfuji commented on configs/templates/unified-dev/spack.yaml
> +    # Add the github-cli as a top-level package for users that do not have
I don't understand this comment

2024-08-23 14:35 UTC, climbfuji commented
It seems like the permissions in the extracted gh cli source code are causing other PR's github actions to fail:

https://github.com/JCSDA/spack-stack/actions/runs/10526384237/job/29167119508?pr=1257

I'll remove the build caches manually on the systems for now so that #1257 can proceed, please fix this before pushing to the branch again:
```
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/cyberphone: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/example_test.go: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/errors_test.go: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/LICENSE: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/format_test.go: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/Makefile: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/go113_test.go: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/README.md: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/json_test.go: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/appveyor.yml: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/.gitignore: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/stack.go: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/stack_test.go: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/go113.go: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/bench_test.go: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/.travis.yml: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1/errors.go: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg/errors@v0.9.1: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/pkg: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg: Permission denied
rm: cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q: Permission denied
```

2024-08-23 14:37 UTC, climbfuji commented
Looks like all the offending files are missing the write permission:
```
ip-10-0-0-117:spack-stack ec2-user$ ls -la cache/build_stage/spack-stage-gh-2.50.0-gmwttfxsdsroeb4d6wsgtl66ydnxo26q/pkg/mod/github.com/cyberphone
total 0
drwxr-xr-x   3 ec2-user  staff    96 Aug 23 04:33 .
drwxr-xr-x  79 ec2-user  staff  2528 Aug 23 04:33 ..
dr-xr-xr-x  16 ec2-user  staff   512 Aug 23 04:33 json-canonicalization@v0.0.0-20220623050100-57a0ce2678a7
```

2024-08-23 20:25 UTC, eap commented on configs/templates/unified-dev/spack.yaml
> +    # Add the github-cli as a top-level package for users that do not have
removed per your other suggestion

2024-08-23 20:26 UTC, eap commented
Thanks for the review - I've updated this per your suggestion; I'm still learning the various enviornment modules we manage. I'll watch the workflow results here to see if that CI fix we merged works as expected.

2024-08-23 21:00 UTC, climbfuji approved these changes, later dismissed
Looks good to me, thanks for making the updates. I'll go ahead and approve. Auto-merge will take care of the rest, assuming that the tests all pass.

2024-08-24 01:54 UTC, climbfuji commented
I see that the ubuntu intel CI test fails because of go. We should stay away from go. That's the reason why git-lfs is always an external package. go is difficult to build, if we can avoid it then let's do it. If not, we need to look into building go with GNU (along the lines of #1257

2024-11-26 17:03 UTC, climbfuji commented
Will be replaced by another PR

2024-11-26 17:03 UTC, closed without merging