Spack v0.18
JCSDA/spack-stack pull request #165
Opened 2022-06-01 03:23 UTC by kgerheiser

Update Spack to v0.18

https://github.com/spack/spack/releases/tag/v0.18.0

* Modules install location is now in modules.yaml
* Reuse is now the default when concretizing
* Concretize option changed in environment. Trying out `when_possible` to reuse when possible.
* Better concretization error messages
* Improvements for external Python linking

Fix #161

2022-06-01 04:03 UTC, kgerheiser commented
Builds are running

2022-06-01 12:49 UTC, kgerheiser commented
All the builds passed except one which failed for an unrelated reason because of a connection an error.

2022-06-01 12:50 UTC, climbfuji commented
I suggest we add checkboxes to the PR description with the HPCs we want to test? Better than fixing post-commit? We can split the work ...

2022-06-01 13:23 UTC, kgerheiser commented
Ok, sounds good. I added some boxes for a couple machines. Testing the build is easy enough. Do you do other testing like running a model?

2022-06-01 13:31 UTC, climbfuji commented
> Ok, sounds good. I added some boxes for a couple machines. Testing the build is easy enough. Do you do other testing like running a model?

I usually run the ufs-weather-model `control_c48` run and the `fv3-bundle` ctests. But we don't need to do all of this on every platform. I'll start with gaea. Will also add a few other platforms that JCSDA needs.

2022-06-01 14:31 UTC, kgerheiser commented
The `+pmix` variant in external OpenMPI, as on Orion, was removed.

2022-06-01 19:36 UTC, kgerheiser commented
Built and ran ufs-weather-model control_c48 on Orion.

2022-06-02 17:01 UTC, climbfuji commented
@kgerheiser I think I am ok with merging this. It built on two largely different HPCs with two very different env specs, and it built on your Mac and in the CI tests (correct?)

2022-06-02 17:09 UTC, kgerheiser commented
Yes, [Ubuntu Intel](https://github.com/kgerheiser/spack-stack/actions/runs/2419124692), [Ubuntu GCC](https://github.com/kgerheiser/spack-stack/actions/runs/2419124548), [macOS GCC](https://github.com/kgerheiser/spack-stack/actions/runs/2419124827).

[apple-clang](https://github.com/kgerheiser/spack-stack/runs/6682466300?check_suite_focus=true) failed from a network error during a download.


I compiled on my Mac with apple-clang and Orion with Intel.

2022-06-02 17:13 UTC, climbfuji commented
And I did gaea with intel as indicated in the PR description above.

2022-06-02 17:17 UTC, climbfuji requested changes
spack submodule pointer is correct, just restore the newline in `.gitmodules` please and we are good to go!

2022-06-02 17:17 UTC, climbfuji commented on .gitmodules
> +  branch = jcsda_emc_spack_stack
```suggestion
  branch = jcsda_emc_spack_stack

```

2022-06-02 17:18 UTC, kgerheiser commented
But I'm getting a conflict some reason.

2022-06-02 17:19 UTC, climbfuji commented
probably need to pull in the updates from spack-stack develop first.

2022-06-02 17:26 UTC, merged

2022-06-02 17:27 UTC, kgerheiser commented
This was good to get done. I have a couple of minor things I want to merge now that this is done.

2022-06-02 17:30 UTC, climbfuji commented
Same here. Can you please add the corresponding issues/PR to the project kanban (first spack release) so that we can keep track of it? Also, please provide feedback if you think that something shouldn't go into the release that is already in the kanban. Thanks!

2022-06-02 17:48 UTC, kgerheiser commented
Yes