added issue templates
JCSDA/spack-stack pull request #252
Opened 2022-07-12 17:59 UTC by edwardhartnett

Fixes #251 

Adding issue templates from hpc-stack.

2022-07-12 18:04 UTC, aerorahul approved these changes
Looks good.

2022-07-12 18:14 UTC, kgerheiser commented on .github/ISSUE_TEMPLATE/add_package_request.md
> +about: Request that a package be added to hpc-stack
Replace hpc-stack with spack-stack (or Spack)

2022-07-12 18:14 UTC, kgerheiser commented on .github/ISSUE_TEMPLATE/add_package_request.md
> +**Please describe the package or library you would like to add to hpc-stack.**
Same here

2022-07-12 18:14 UTC, kgerheiser commented on .github/ISSUE_TEMPLATE/add_package_request.md
> +List any other related pacakges already in hpc-stack, as far as you know.
And here

2022-07-12 18:21 UTC, climbfuji requested changes

2022-07-12 18:21 UTC, climbfuji commented on .github/ISSUE_TEMPLATE/add_package_request.md
> +assignees: 'Hang-Lei-NOAA'
I think this needs updating.

2022-07-12 18:21 UTC, climbfuji commented on .github/ISSUE_TEMPLATE/add_package_request.md
> +**What applications at NOAA will be using this package or library?**
Remove "at NOAA" or expand as appropriate, please

2022-07-12 18:21 UTC, climbfuji commented on .github/ISSUE_TEMPLATE/add_package_request.md
> +**Will This Package be Needed in an Operational Application?**
NOAA-specific, but ok to keep I think

2022-07-12 18:21 UTC, climbfuji commented on .github/ISSUE_TEMPLATE/install_request.md
> +assignees: 'Hang-Lei-NOAA, kgerheiser, jkbk2004'
Needs updating

2022-07-12 18:32 UTC, climbfuji commented
FYI, you can add "[skip ci]" to your commit messages to skip running CI for these PRs that don't touch any code (it will then only build the documentation).

2022-07-12 18:34 UTC, kgerheiser commented
@climbfuji does that also allow merging without the required checks?

2022-07-12 18:35 UTC, climbfuji commented
> @climbfuji does that also allow merging without the required checks?

I believe it does ... we'll find out.

2022-07-12 18:47 UTC, kgerheiser commented
The check will still be required. There's no 'good' workaround, what Github suggests is to create a dummy workflow.

https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

2022-07-12 18:50 UTC, climbfuji commented
> The check will still be required. There's no 'good' workaround, what Github suggests is to create a dummy workflow.
> 
> https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

Annoying. Well, we may keep the options on for administrators to override the required status checks. We can then decide whether an author's decision to not run CI is justified and merge w/o the status checks to pass. Just another option instead of creating complicated dummy workflows.

2022-07-13 13:10 UTC, edwardhartnett commented on .github/ISSUE_TEMPLATE/add_package_request.md
> +**What applications at NOAA will be using this package or library?**
OK

2022-07-13 13:10 UTC, edwardhartnett commented on .github/ISSUE_TEMPLATE/add_package_request.md
> +**Will This Package be Needed in an Operational Application?**
I have specified that this is for NOAA only...

2022-07-13 13:11 UTC, edwardhartnett commented on .github/ISSUE_TEMPLATE/install_request.md
> +assignees: 'Hang-Lei-NOAA, kgerheiser, jkbk2004'
You want your name there too?

2022-07-13 13:44 UTC, climbfuji commented on .github/ISSUE_TEMPLATE/install_request.md
> +assignees: 'Hang-Lei-NOAA, kgerheiser, jkbk2004'
Would be good, yes. Once I had a chance to talk to my colleague (on leave this week), I'll add him as well.

2022-07-13 14:00 UTC, edwardhartnett commented on .github/ISSUE_TEMPLATE/install_request.md
> +assignees: 'Hang-Lei-NOAA, kgerheiser, jkbk2004'
Who is JONG KIM jkbk2004?

Should he be listed here?

2022-07-13 14:19 UTC, climbfuji commented on .github/ISSUE_TEMPLATE/install_request.md
> +assignees: 'Hang-Lei-NOAA, kgerheiser, jkbk2004'
Jong Kim is from the EPIC team, he is doing the installs of hpc-stack on Cheyenne as far as I know.

2022-07-13 14:35 UTC, climbfuji approved these changes
Thanks for addressing my comments.

2022-07-14 14:00 UTC, kgerheiser approved these changes

2022-07-14 14:02 UTC, merged