testing gnu container
JCSDA/spack-stack pull request #281
Opened 2022-07-26 20:16 UTC by mer-a-o

2022-08-11 21:48 UTC, mer-a-o commented
I was able to build a gnu container with spack. All the jedi-bundle tested passed except for 3 soca tests:
```
	1366 - test_soca_3dvarlowres_soca (Failed)
	1374 - letkf_split_observer_post (Failed)
	1375 - test_soca_letkf_split_solver (Failed)
```
failure in `letkf_split_observer_post` is related to not finding `ncks` command. 
The other two failures happen at the compare step.

2022-08-15 15:31 UTC, climbfuji commented
> I was able to build a gnu container with spack. All the jedi-bundle tested passed except for 3 soca tests:
> 
> ```
> 	1366 - test_soca_3dvarlowres_soca (Failed)
> 	1374 - letkf_split_observer_post (Failed)
> 	1375 - test_soca_letkf_split_solver (Failed)
> ```
> 
> failure in `letkf_split_observer_post` is related to not finding `ncks` command. The other two failures happen at the compare step.

That's great! I think your container needs to install `nco` (we use version 5.0.6 in skylab-1.0.x).

2022-08-15 15:35 UTC, mer-a-o commented
I'm testing mpas-bundle with the new container and I get an error when configuring mpas-model
```
-- Adding bundle project MPAS
-- Cloning MPAS from https://github.com/JCSDA-internal/MPAS-Model.git into /home/nonroot/mpas-bundle/MPAS...
-- /home/nonroot/mpas-bundle/MPAS retrieved.
-- Updating MPAS to head of BRANCH release-stable...
-- git fetch --all @ /home/nonroot/mpas-bundle/MPAS
-- git fetch --all --tags @ /home/nonroot/mpas-bundle/MPAS
-- git checkout release-stable @ /home/nonroot/mpas-bundle/MPAS
-- [OPTION] MPAS_CORES: init_atmosphere;atmosphere
-- [OPTION] MPAS_DOUBLE_PRECISION: ON
-- [OPTION] MPAS_PROFILE: OFF
-- [OPTION] MPAS_OPENMP: OFF
-- [OPTION] BUILD_SHARED_LIBS: ON
-- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5") found components: Fortran 
-- Found MPI: TRUE (found version "3.1") found components: Fortran 
-- Found NetCDF: /opt/view/include (found version "4.8.1") found components: Fortran 
-- FindNetCDF [/home/nonroot/mpas-bundle/MPAS/cmake/Modules/FindNetCDF.cmake]:
--   - NetCDF_VERSION [4.8.1]
--   - NetCDF_PARALLEL [TRUE]
--   - NetCDF_C_CONFIG_EXECUTABLE [/opt/view/bin/nc-config]
--   - NetCDF::NetCDF_C [SHARED] [Root: /opt/view] Lib: /opt/view/lib/libnetcdf.so 
--   - NetCDF_Fortran_CONFIG_EXECUTABLE [/opt/view/bin/nf-config]
--   - NetCDF::NetCDF_Fortran [SHARED] [Root: /opt/view] Lib: /opt/view/lib/libnetcdff.so 
-- Found PnetCDF: /opt/view/bin/pnetcdf-config (found version "1.12.2") found components: Fortran 
-- FindPnetCDF:
--   - PnetCDF_VERSION [1.12.2]
--   - PnetCDF_PREFIX [/opt/software/linux-ubuntu20.04-haswell/gcc-9.4.0/parallel-netcdf-1.12.2-mkojzjqqbccur5n73fbi2h5qbwhjdobr]
--   - PnetCDF Components Found: Fortran;C;CXX
-- Found PIO: /opt/view  found components: Fortran C 
-- FindPIO:
--   - PIO_PREFIX [/opt/view]
--   - PIO Components Found: Fortran;C;SHARED
CMake Error at MPAS/CMakeLists.txt:67 (find_program):
  Could not find CPP_EXECUTABLE using the following names: cpp
```

2022-08-15 15:35 UTC, climbfuji commented
> I'm testing mpas-bundle with the new container and I get an error when configuring mpas-model
> 
> ```
> -- Adding bundle project MPAS
> -- Cloning MPAS from https://github.com/JCSDA-internal/MPAS-Model.git into /home/nonroot/mpas-bundle/MPAS...
> -- /home/nonroot/mpas-bundle/MPAS retrieved.
> -- Updating MPAS to head of BRANCH release-stable...
> -- git fetch --all @ /home/nonroot/mpas-bundle/MPAS
> -- git fetch --all --tags @ /home/nonroot/mpas-bundle/MPAS
> -- git checkout release-stable @ /home/nonroot/mpas-bundle/MPAS
> -- [OPTION] MPAS_CORES: init_atmosphere;atmosphere
> -- [OPTION] MPAS_DOUBLE_PRECISION: ON
> -- [OPTION] MPAS_PROFILE: OFF
> -- [OPTION] MPAS_OPENMP: OFF
> -- [OPTION] BUILD_SHARED_LIBS: ON
> -- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
> -- Found OpenMP: TRUE (found version "4.5") found components: Fortran 
> -- Found MPI: TRUE (found version "3.1") found components: Fortran 
> -- Found NetCDF: /opt/view/include (found version "4.8.1") found components: Fortran 
> -- FindNetCDF [/home/nonroot/mpas-bundle/MPAS/cmake/Modules/FindNetCDF.cmake]:
> --   - NetCDF_VERSION [4.8.1]
> --   - NetCDF_PARALLEL [TRUE]
> --   - NetCDF_C_CONFIG_EXECUTABLE [/opt/view/bin/nc-config]
> --   - NetCDF::NetCDF_C [SHARED] [Root: /opt/view] Lib: /opt/view/lib/libnetcdf.so 
> --   - NetCDF_Fortran_CONFIG_EXECUTABLE [/opt/view/bin/nf-config]
> --   - NetCDF::NetCDF_Fortran [SHARED] [Root: /opt/view] Lib: /opt/view/lib/libnetcdff.so 
> -- Found PnetCDF: /opt/view/bin/pnetcdf-config (found version "1.12.2") found components: Fortran 
> -- FindPnetCDF:
> --   - PnetCDF_VERSION [1.12.2]
> --   - PnetCDF_PREFIX [/opt/software/linux-ubuntu20.04-haswell/gcc-9.4.0/parallel-netcdf-1.12.2-mkojzjqqbccur5n73fbi2h5qbwhjdobr]
> --   - PnetCDF Components Found: Fortran;C;CXX
> -- Found PIO: /opt/view  found components: Fortran C 
> -- FindPIO:
> --   - PIO_PREFIX [/opt/view]
> --   - PIO Components Found: Fortran;C;SHARED
> CMake Error at MPAS/CMakeLists.txt:67 (find_program):
>   Could not find CPP_EXECUTABLE using the following names: cpp
> ```

Same as for gcc, gfortran etc I guess - probably needs an alias for cpp-10 ?

2022-08-15 16:05 UTC, mer-a-o commented
@climbfuji adding cpp to /usr/bin and linking it to cpp-10 solved the issue. I'm getting a new error at `make` step:
```
/home/nonroot/mpas-bundle/MPAS/src/external/esmf_time_f90/MeatMod.F90:28:22:

   28 |   INTEGER(ESMF_KIND_I8), INTENT(IN) :: numerator
      |                      1
Error: Symbol 'esmf_kind_i8' at (1) has no IMPLICIT type
/home/nonroot/mpas-bundle/MPAS/src/external/esmf_time_f90/MeatMod.F90:29:22:

   29 |   INTEGER(ESMF_KIND_I8), INTENT(IN) :: denominator
      |                      1
Error: Symbol 'esmf_kind_i8' at (1) has no IMPLICIT type
/home/nonroot/mpas-bundle/MPAS/src/external/esmf_time_f90/MeatMod.F90:58:22:

   58 |   INTEGER(ESMF_KIND_I8) :: numerator_i8, denominator_i8
      |                      1
Error: Symbol 'esmf_kind_i8' at (1) has no IMPLICIT type
/home/nonroot/mpas-bundle/MPAS/src/external/esmf_time_f90/MeatMod.F90:26:42:

   26 | SUBROUTINE fraction_to_stringi8( numerator, denominator, frac_str )
      |                                          1
Error: Symbol 'numerator' at (1) has no IMPLICIT type
/home/nonroot/mpas-bundle/MPAS/src/external/esmf_time_f90/MeatMod.F90:26:55:

   26 | SUBROUTINE fraction_to_stringi8( numerator, denominator, frac_str )
      |                                                       1
Error: Symbol 'denominator' at (1) has no IMPLICIT type
/home/nonroot/mpas-bundle/MPAS/src/external/esmf_time_f90/MeatMod.F90:60:16:

   60 |   denominator_i8 = INT( denominator, ESMF_KIND_I8 )
      |                1
Error: Symbol 'denominator_i8' at (1) has no IMPLICIT type; did you mean 'denominator'?
/home/nonroot/mpas-bundle/MPAS/src/external/esmf_time_f90/MeatMod.F90:59:45:

   59 |   numerator_i8 = INT( numerator, ESMF_KIND_I8 )
      |                                             1
Error: Symbol 'esmf_kind_i8' at (1) has no IMPLICIT type
/home/nonroot/mpas-bundle/MPAS/src/external/esmf_time_f90/MeatMod.F90:59:14:

   59 |   numerator_i8 = INT( numerator, ESMF_KIND_I8 )
      |              1
Error: Symbol 'numerator_i8' at (1) has no IMPLICIT type; did you mean 'numerator'?
make[2]: *** [MPAS/src/external/esmf_time_f90/CMakeFiles/esmf.dir/build.make:231: MPAS/src/external/esmf_time_f90/CMakeFiles/esmf.dir/MeatMod.F90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:18359: MPAS/src/external/esmf_time_f90/CMakeFiles/esmf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

2022-08-15 17:13 UTC, climbfuji commented
I wonder if the version of mpas used in mpas-bundle requires a specific version of ESMF.

2022-08-15 18:45 UTC, mer-a-o commented
I removed `esmf` files from `/opt/view` and rebuilt mpas-bundle. I'm getting a new error:
```
/usr/bin/ld: cannot find -lnetcdf
/usr/bin/ld: cannot find -lnetcdf
[ 18%] Built target test_util_floatcompare
collect2: error: ld returned 1 exit status
make[2]: *** [MPAS/src/framework/CMakeFiles/framework.dir/build.make:574: lib/libmpas_framework.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:18521: MPAS/src/framework/CMakeFiles/framework.dir/all] Error 2
```

2022-08-15 18:48 UTC, climbfuji commented
> I removed `esmf` files from `/opt/view` and rebuilt mpas-bundle. I'm getting a new error:
> 
> ```
> [ 18%] Linking CXX executable test_util_floatcompare
> [ 18%] Building Fortran object ropp-ufo/src/CMakeFiles/ropp-ufo.dir/ropp_io/ropp/ropp_io_success.f90.o
> [ 18%] Building Fortran object ropp-ufo/src/CMakeFiles/ropp-ufo.dir/ropp_io/thin/ropp_io_thin_sg.f90.o
> [ 18%] Linking Fortran shared library ../../../lib/libmpas_framework.so
> /usr/bin/ld: cannot find -lnetcdf
> /usr/bin/ld: cannot find -lnetcdf
> [ 18%] Built target test_util_floatcompare
> collect2: error: ld returned 1 exit status
> make[2]: *** [MPAS/src/framework/CMakeFiles/framework.dir/build.make:574: lib/libmpas_framework.so] Error 1
> make[1]: *** [CMakeFiles/Makefile2:18521: MPAS/src/framework/CMakeFiles/framework.dir/all] Error 2
> 
> /usr/bin/ld: cannot find -lnetcdf
> /usr/bin/ld: cannot find -lnetcdf
> [ 18%] Built target test_util_floatcompare
> collect2: error: ld returned 1 exit status
> make[2]: *** [MPAS/src/framework/CMakeFiles/framework.dir/build.make:574: lib/libmpas_framework.so] Error 1
> make[1]: *** [CMakeFiles/Makefile2:18521: MPAS/src/framework/CMakeFiles/framework.dir/all] Error 2
> ```

That could be an error in the mpas-bundle `CMakeLists.txt` not asking for the netcdf library (maybe because it was added implicitly through the ESMF dependency?)

2022-08-15 18:49 UTC, climbfuji commented
How about we get this PR ready to merge, noting that the current version of the container builds jedi/fv3-bundle? Then we can make the necessary updates for mpas-bundle later.

2022-08-15 18:53 UTC, mer-a-o commented
Sure, we can do that. Please note that mpas CI uses the same container as all the other CIs. So we cannot yet update the CI container.

2022-08-15 20:01 UTC, climbfuji commented
> Sure, we can do that. Please note that mpas CI uses the same container as all the other CIs. So we cannot yet update the CI container.

Yes, that's totally fine. Since the generic container config in this PR doesn't contain the specs to install, we either need another container recipe that builds on the generic one, or have instructions somewhere (jedi-docs or here? tbd).

2022-08-15 20:26 UTC, mer-a-o commented
@climbfuji This PR is ready.

2022-08-15 20:38 UTC, climbfuji requested changes
Please remove the unnecessary comment, and commit the change with `[skip ci]` in the commit message

2022-08-15 20:38 UTC, climbfuji commented on configs/containers/docker-ubuntu-gcc-openmpi.yaml
> +        #ref: spack-stack-1.0.1
Please remove this line

2022-08-15 21:05 UTC, climbfuji approved these changes

2022-08-16 17:20 UTC, srherbener approved these changes
I'm not very expert at the container building process, but the code looks okay to me (plus it's been tested pretty thoroughly). Thanks for all the hard work on this!

2022-08-16 17:24 UTC, merged