Update zlib version and macos instructions for handling the new Mac M1 native arm64 architecture
JCSDA/spack-stack pull request #399
Opened 2022-11-07 22:48 UTC by srherbener

This PR contains updates to enable the successful build of the stack on the new Mac M1 arm64 architecture. The zlib version needs to be 1.12.13 for arm64 so this has been updated in the `configs/common/packages.yaml` file. The other config files were left alone since I was thinking these are deliberately set to specific versions according to different platforms. The documentation has been updated to reflect new steps necessary for building spack-stack on the M1 arm64 architecture.

2022-11-07 22:55 UTC, climbfuji requested changes
This is a great write-up! Thanks very much for contributing this. I will note, however, that on the latest macOS Ventura, it is no longer possible to duplicate the Terminal application. One option is to install both iTerm or Terminal and use one for Rosetta2 x86_64, one for native arch64, another option is to configure two profiles in your preferred terminal app to toggle between them (suggested by @ytremolet).

2022-11-07 22:55 UTC, climbfuji commented on doc/source/Platforms.rst
> +For example, entering ``arch`` without any arguments will return which archtecture is running in your terminal window.
```suggestion
For example, entering ``arch`` without any arguments will return which architecture is running in your terminal window.
```

2022-11-08 17:17 UTC, climbfuji approved these changes

2022-11-09 15:03 UTC, mer-a-o approved these changes
@srherbener Thank you for updating the document. It is a lot clearer now.

2022-11-09 15:25 UTC, climbfuji commented
I am rerunning the failed CI tests, they got canceled for no obvious reason. Shouldn't take too long.

2022-11-09 18:23 UTC, merged