Add pixman variant enabling position-independent code (PIC) compiler flag
JCSDA/spack-stack pull request #625
Opened 2023-06-06 21:53 UTC by eap

This issue appears to have been included in the 1.4.0 release but it only affects platforms without pixman installed. I suspect this issue hasn't come up because many of our targets already have pixman and preventing spack from attempting to build it. Without this flag we will get the following error during spack install.

```
/usr/bin/ld: .libs/pixman-implementation.o: relocation R_X86_64_TPOFF32 against `fast_path_cache' can not be used when making a shared object; recompile with -fPIC
```

After making this change locally I have observed the following concretize output for pixman

```
-   z7omuo7                      ^pixman@0.42.2%gcc@11.3.0+pic+shared build_system=autotools arch=linux-ubuntu22.04-icelake
```

2023-06-21 16:04 UTC, climbfuji requested changes

2023-06-21 16:04 UTC, climbfuji commented on configs/common/packages.yaml
> +      version: [2.14.2]
I wouldn't add a version here, just the variant.

2023-06-21 16:04 UTC, climbfuji commented on configs/common/packages.yaml
> +      version: [2.11.1]
I wouldn't add a version here, just the variant.

2023-06-29 18:39 UTC, climbfuji commented
@eap Can you address the comments in the PR review please? I think it's ok to merge the `+pic` flags, but we don't want those versions hardcoded. Thanks

2023-07-11 00:24 UTC, climbfuji requested changes

2023-07-11 00:24 UTC, climbfuji commented on configs/common/packages.yaml
> +      version: [0.42.2]
```suggestion
```

2023-07-11 00:24 UTC, climbfuji commented on configs/common/packages.yaml
> +      version: [2.11.1]
```suggestion
```

2023-07-11 00:24 UTC, climbfuji commented on configs/common/packages.yaml
> +      version: [2.14.2]
```suggestion
```

2023-07-14 18:43 UTC, eap commented
A different way to fix this to edit the `site/compilers.yaml` and add the cc flags manually:

example (includes -O3)
```
flags:
      cflags: -O3 -fPIC
      cxxflags: -O3 -fPIC
      cppflags: -O3 -fPIC
 ```
 
 The last time I edited this I was still struggling to find all packages that needed the variant. I'm not sure if I should attempt to continue or not.

2023-07-14 18:45 UTC, climbfuji commented
> A different way to fix this to edit the `site/compilers.yaml` and add the cc flags manually:
> 
> example (includes -O3)
> 
> ```
> flags:
>       cflags: -O3 -fPIC
>       cxxflags: -O3 -fPIC
>       cppflags: -O3 -fPIC
> ```
> 
> The last time I edited this I was still struggling to find all packages that needed the variant. I'm not sure if I should attempt to continue or not.

It's fine to close it. We can fix it later if it comes up again. I don't want to throw blanket `-fPIC` flags over everything using the default compiler flags.

2023-07-14 18:50 UTC, eap commented
Sounds good - closing now. We can revisit later if needed. For the moment I've only had this issue on one platform. If it comes up elsewhere we can reopen.

2023-07-14 18:50 UTC, closed without merging