Update project charter following JCSDA/EMC/EPIC meeting 2023/07/19
JCSDA/spack-stack pull request #685
Opened 2023-07-22 03:20 UTC by climbfuji

### Summary

Update project charter with what was discussed on July 19 between JCSDA, NOAA-EMC, and EPIC. Please update/correct this as needed and merge when satisfied (@srherbener can approve for JCSDA).

You can render the markdown in any mark down live preview page.

### Testing

n/a

### Applications affected

n/a

### Systems affected

n/a

### Dependencies

n/a

### Issue(s) addressed

#493 

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [ ] ~~These changes have been tested on the affected systems and applications.~~
- [ ] ~~All dependency PRs/issues have been resolved and this PR can be merged.~~

2023-07-22 03:25 UTC, climbfuji commented
@arunchawla-NOAA @junwang-noaa @ytremolet FYI

2023-07-24 16:19 UTC, srherbener reviewed
I think the updates look great, just found a couple typos.

2023-07-24 16:19 UTC, srherbener commented on project_charter.md
> +The advantace is that it is obvious to the developer, the reviewers and the code managers that a library update in a PR is not officially rolled out everywhere yet. Further, there is no risk to corru
```suggestion
The advantage is that it is obvious to the developer, the reviewers and the code managers that a library update in a PR is not officially rolled out everywhere yet. Further, there is no risk to corrupt official spack-stack installations with frequent test installs. 
```

2023-07-24 16:19 UTC, srherbener commented on project_charter.md
> +* Unless it is a patch release (increasing the z in x.y.z,) create a project board for the release at https://github.com/JCSDA/spack-stack/actions.
```suggestion
* Unless it is a patch release (increasing the z in x.y.z,) create a project board for the release at https://github.com/JCSDA/spack-stack/projects.
```

2023-07-24 16:43 UTC, ulmononian requested changes

2023-07-24 16:43 UTC, ulmononian commented on project_charter.md
> +Test installations can be requested as part of issues (which should be mandatory for pull requests anyway). This can be more frequent than official updates.
```suggestion
Test installations can be requested as part of issues (which should be mandatory for pull requests anyway). These can be more frequent than official updates.
```

2023-07-24 16:43 UTC, ulmononian commented on project_charter.md
> +Official updates need to be made consistently across all platforms. There shall never be a situation when an official spack-stack installation on one platform differs from the others in their package
```suggestion
Official updates need to be made consistently across all platforms. There shall never be a situation when an official spack-stack installation on one platform differs from the others in their packages, package configurations, etc. (unless required by and encoded in spack-stack itself).
```

2023-07-24 16:43 UTC, ulmononian commented on project_charter.md
> +Regular, full releases of spack-stack are made every three months around end of February, May, August, November.
```suggestion
Regular, full releases of spack-stack are made every three months around the end of February, May, August, and November.
```

2023-07-24 16:43 UTC, ulmononian commented on project_charter.md
> +spack-stack developers are committed to maintaining a rolling stock of the last four releases, i.e. one year worth of spack-stack releases. Under special circumstances (e.g. operational implementatio
```suggestion
spack-stack developers are committed to maintaining a rolling stock of the last four releases, i.e. one year's worth of spack-stack releases. Under special circumstances (e.g. operational implementations that require long-term support, long-running official retrospectives), selected releases may be kept longer.
```

2023-07-24 17:55 UTC, AlexanderRichert-NOAA commented on project_charter.md
> +install on their systems (see https://spack-stack.readthedocs.io/en/latest/#).
I assume this link should be https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html

2023-07-24 17:56 UTC, AlexanderRichert-NOAA commented on project_charter.md
> +* Add a new epic (github issue) explaining the reason for the release, and to notify all other stakeholders.
->"Add a new EPIC GitHub issue"?

2023-07-24 18:11 UTC, srherbener approved these changes

2023-07-24 21:25 UTC, ulmononian approved these changes

2023-07-24 21:26 UTC, merged