Lmod tcl config
JCSDA/spack-stack pull request #796
Opened 2023-09-29 18:01 UTC by AlexanderRichert-NOAA

### Summary

This PR separates common/modules.yaml into tcl and lmod versions. Based on the corresponding change in the create env command (https://github.com/JCSDA/spack/pull/329), it will automatically detect for a given site whether to use lmod or tcl, with an option to override.

### Testing

Describe the testing done for this PR.

### Applications affected

List all known applications (UFS WM, JEDI, SRW, etc.) intentionally or unintentionally affected by this PR.

### Systems affected

List all systems intentionally or unintentionally affected by this PR.

### Dependencies

https://github.com/JCSDA/spack/pull/329

### Issue(s) addressed

Fixes #703, #50

### Checklist
- [ ] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [ ] These changes have been tested on the affected systems and applications.
- [ ] All dependency PRs/issues have been resolved and this PR can be merged.

2023-09-29 20:13 UTC, srherbener approved these changes
Changes look good. Again didn't test (relying on CI testing).

2023-09-29 20:47 UTC, climbfuji reviewed
I like this! Can you also update the documentation and the unit tests, please?

2023-10-02 02:27 UTC, climbfuji requested changes
I ran the following on my macOS:
```
spack stack create env --name=test-tcl --template=unified-dev --site=macos.default --modulesys=tcl
```
This worked although it should have failed, because now `envs/test-tcl/common/packages.yaml` uses `tcl`, but `envs/test-tcl/site/packages.yaml` uses `lmod`. This won't work. We need to think about what the viable options should be for this utiity.

I would also like to suggest that, after the code changes are finalized the documentation is updated in the different sections.

But overall neat, and thanks for adding the unit tests in the spack submodule.

2023-10-02 02:27 UTC, climbfuji commented on .gitmodules
> +[submodule "spack/"]
Lines 11-12 need to be removed

2023-10-02 15:42 UTC, AlexanderRichert-NOAA commented
I'm not sure I follow? The idea is that tcl/lmod will be set automatically, but I added the '--modulesys' argument for users with weird use cases who want to do their own thing (with the expectation that they will need to do whatever they need to do to make their specific case work). That said, I'd be just as happy leaving that option out, setting it only automatically, and any user who wants something different can copy/modify config files as needed.

2023-10-02 16:40 UTC, climbfuji commented
> I'm not sure I follow? The idea is that tcl/lmod will be set automatically, but I added the '--modulesys' argument for users with weird use cases who want to do their own thing (with the expectation that they will need to do whatever they need to do to make their specific case work). That said, I'd be just as happy leaving that option out, setting it only automatically, and any user who wants something different can copy/modify config files as needed.

Do you think this can wait until Thursday? It's probably way more efficient to talk about this in the spack-stack meeting.

2023-10-06 20:57 UTC, AlexanderRichert-NOAA commented
@climbfuji having it update the site config turned out to not be too difficult, but obviously let me know if I missed something. There's also a CI check that does a diff on the modules_{tcl,lmod}.yaml files. It looks like somehow my documentation update didn't get pushed previously but it should be there now.

2023-10-11 03:12 UTC, climbfuji reviewed
I've tested this on my macOS and it works great. Will approve once the submodule pointer is updated etc. Thanks very much for this!

2023-10-11 14:56 UTC, climbfuji commented
I merged the spack PR, new hash for spack is https://github.com/JCSDA/spack/commit/0669acaacf0a1f0cc9f7fca0294458bf50418951

2023-10-11 16:54 UTC, AlexanderRichert-NOAA commented
Updated submodule

2023-10-11 16:55 UTC, climbfuji approved these changes

2023-10-11 19:09 UTC, merged